Update apply.yaml

diff --git a/.github/workflows/apply.yaml b/.github/workflows/apply.yaml
--- a/.github/workflows/apply.yaml
+++ b/.github/workflows/apply.yaml
@@ -52,24 +52,22 @@ jobs:
       - name: Terraform Plan
         id: plan
         run: |
-          # Terraform planを実行し、出力を表示
-          terraform plan -detailed-exitcode -out saved_plan || exit_code=$?
+          terraform plan -detailed-exitcode -out saved_plan
+          plan_exit_code=$?
           
-          # exit_codeの値に基づいて処理を分岐
-          case ${exit_code:-0} in
-            0)
-              echo "No changes. Infrastructure is up-to-date."
-              echo "changes=false" >> $GITHUB_OUTPUT
-              ;;
-            1)
-              echo "Terraform plan failed."
-              exit 1
-              ;;
-            2)
-              echo "Changes detected in plan."
-              echo "changes=true" >> $GITHUB_OUTPUT
-              ;;
-          esac
+          echo "Plan exit code: $plan_exit_code"
+          
+          # 終了コードに基づいて処理を分岐
+          if [ $plan_exit_code -eq 0 ]; then
+            echo "No changes. Infrastructure is up-to-date."
+            echo "changes=false" >> $GITHUB_OUTPUT
+          elif [ $plan_exit_code -eq 2 ]; then
+            echo "Changes detected in plan."
+            echo "changes=true" >> $GITHUB_OUTPUT
+          else
+            echo "Terraform plan failed."
+            exit 1
+          fi
       
       - name: Upload saved plan
         uses: actions/upload-artifact@v4.6.1
